package com.logica;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

//Hecho por Walter Sebastian Melendez Julca-20231805 

public class RegistroIU extends javax.swing.JFrame {
    // Atributos principales
    private Mesa_Partes mesa;
    private RegistroInteresado registroPersona;
    private ArbolExpedientes arbol;
    // Botones de tipo y prioridad
    private ButtonGroup grupoTipo;
    private ButtonGroup grupoPrioridad;

      
   public RegistroIU() {
    // Crear la estructura y lógica principal una sola vez
    this.mesa = new Mesa_Partes(); 
    this.registroPersona = new RegistroInteresado(mesa); 
    
    initComponents(); // Carga la interfaz

    // Configurar los grupos de radio buttons
    grupoTipo = new ButtonGroup();
    grupoTipo.add(bUlima);
    grupoTipo.add(bExterno);

    grupoPrioridad = new ButtonGroup();
    grupoPrioridad.add(bAlta);
    grupoPrioridad.add(bBaja);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        dniTxt = new javax.swing.JTextField();
        nombreTxt = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        btnLlenar = new javax.swing.JButton();
        btnVerLista = new javax.swing.JButton();
        btnGrabar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dni = new javax.swing.JLabel();
        Prioridad = new javax.swing.JLabel();
        asunto = new javax.swing.JLabel();
        telefono = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        asuntoTxt = new javax.swing.JTextField();
        bUlima = new javax.swing.JRadioButton();
        bExterno = new javax.swing.JRadioButton();
        bAlta = new javax.swing.JRadioButton();
        bBaja = new javax.swing.JRadioButton();
        documentoTxt = new javax.swing.JTextField();
        documento = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        terminadoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dniTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniTxtActionPerformed(evt);
            }
        });
        jPanel1.add(dniTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 340, 40));
        jPanel1.add(nombreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 340, 40));

        email.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 24)); // NOI18N
        email.setText("Email:");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        btnLlenar.setText("Llenar");
        btnLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 71, -1));

        btnVerLista.setText("Ver Lista de pendientes");
        btnVerLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 170, -1));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrabar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 80, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/logoHorizontalOficial.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 45)); // NOI18N
        jLabel3.setText("tramite documentario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 90));

        dni.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 24)); // NOI18N
        dni.setText("DNI:");
        jPanel1.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        Prioridad.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 24)); // NOI18N
        Prioridad.setText("Prioridad");
        jPanel1.add(Prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 200, 30));

        asunto.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 24)); // NOI18N
        asunto.setText("Asunto:");
        jPanel1.add(asunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        telefono.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 24)); // NOI18N
        telefono.setText("Telefono:");
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        telefonoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(telefonoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 340, 40));

        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        jPanel1.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 340, 40));

        asuntoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asuntoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(asuntoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 340, 70));

        bUlima.setText("Ulima");
        jPanel1.add(bUlima, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, -1, -1));

        bExterno.setText("Externo");
        jPanel1.add(bExterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 70, 40));

        bAlta.setText("Alta prioridad");
        jPanel1.add(bAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, -1, -1));

        bBaja.setText("Baja prioridad");
        jPanel1.add(bBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 230, -1, -1));

        documentoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTxtActionPerformed(evt);
            }
        });
        jPanel1.add(documentoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 340, 40));

        documento.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 24)); // NOI18N
        documento.setText("Documento");
        jPanel1.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        Nombre.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 24)); // NOI18N
        Nombre.setText("Nombres:");
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 130, 30));

        Tipo.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 24)); // NOI18N
        Tipo.setText("Tipo persona");
        jPanel1.add(Tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 200, 30));

        terminadoButton.setText("Ver Lista de terminados");
        terminadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminadoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(terminadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void telefonoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTxtActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
       //Se inicia un bloque try-catch con el fin de capturar errores de conversion numerica
       try {
    // Convertir el dni y el telefono a entero desde el campo de texto
    int dni = Integer.parseInt(this.dniTxt.getText());
        int telefono = Integer.parseInt(this.telefonoTxt.getText());

    // Obtener los demás datos desde los campos de texto
    String nombres = this.nombreTxt.getText();
    String email = this.emailTxt.getText();
    String asunto = this.asuntoTxt.getText();
    String documento = this.documentoTxt.getText();

    // Validar que se haya seleccionado un tipo de persona
    String tipoPersona = "";
    if (bUlima.isSelected()) {
        tipoPersona = "Ulima";
    } else if (bExterno.isSelected()) {
        tipoPersona = "Externo";
    } else {
        JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo de persona (Ulima o Externo).", "Campo obligatorio", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar que se haya seleccionado una prioridad
    String prioridad = "";
    if (bAlta.isSelected()) {
        prioridad = "Alta";
    } else if (bBaja.isSelected()) {
        prioridad = "Baja";
    } else {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una prioridad (Alta o Baja).", "Campo obligatorio", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Mostrar los datos por consola (opcional)
    System.out.println("DNI: " + dni);
    System.out.println("Nombres: " + nombres);
    System.out.println("Teléfono: " + telefono);
    System.out.println("Email: " + email);
    System.out.println("Asunto: " + asunto);
    System.out.println("Documento: " + documento);
    System.out.println("Tipo persona: " + tipoPersona);
    System.out.println("Prioridad: " + prioridad);

    // Enviar los datos a la lógica
    this.registroPersona.registrar(dni, nombres, telefono, email, asunto, documento, tipoPersona, prioridad);

    JOptionPane.showMessageDialog(this, "Grabado correctamente!");

    // Limpiar campos
    this.dniTxt.setText("");
    this.nombreTxt.setText("");
    this.telefonoTxt.setText("");
    this.emailTxt.setText("");
    this.asuntoTxt.setText("");
    this.documentoTxt.setText("");
    grupoTipo.clearSelection();
    grupoPrioridad.clearSelection();

} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "El DNI y el teléfono deben ser numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnVerListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerListaActionPerformed
        //Si el arbol de expedientes no a sido crado aun se inicializa con raiz null
        if (this.arbol == null) {
        this.arbol = new ArbolExpedientes(null); // solo si no se ha creado
    }
        // Se crea la ventana de terminados con referencia al arbol de expedientes
    ListaTerminados terminadosUI = new ListaTerminados(arbol);
    // Se crea y muestra la ventana de pendientes pasandole el registro , el arbol y la ventana de terminados
    ListaPendientes ventanaPendientes = new ListaPendientes(registroPersona, arbol, terminadosUI);
    ventanaPendientes.setVisible(true);

    }//GEN-LAST:event_btnVerListaActionPerformed

    private void dniTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniTxtActionPerformed

    private void asuntoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuntoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asuntoTxtActionPerformed

    private void documentoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoTxtActionPerformed

    private void terminadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminadoButtonActionPerformed
        // TODO add your handling code here:
        //Si el arbol de terminados es null da el mensaje de abrir la ventana de pendientes
     if (this.arbol == null) {
        JOptionPane.showMessageDialog(this, "Primero debes abrir la ventana de pendientes.");
        return;
    }
     //Si el arbol ya existe muestra la ventana de expedientes terminados
    ListaTerminados listaTIU = new ListaTerminados(this.arbol);
    listaTIU.setVisible(true);

    }//GEN-LAST:event_terminadoButtonActionPerformed

    private void btnLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarActionPerformed
         // Crear y registrar expedientes de prueba
    registroPersona.registrar(12345678, "Ana Pérez", 999111222, "ana@ulima.edu.pe", "Consulta", "doc1.pdf", "Ulima", "Baja");
    registroPersona.registrar(87654321, "Luis Torres", 987654321, "luis@ulima.edu.pe", "Solicitud urgente", "doc2.pdf", "Ulima", "Alta");
    registroPersona.registrar(44556677, "Carla León", 912345678, "carla@ulima.edu.pe", "Reclamo", "doc3.pdf", "Externo", "Baja");
    registroPersona.registrar(72193859, "Walter Melendez", 946633219, "walter@ulima.edu.pe", "Constancia matrícula", "solicitud.pdf", "Externo", "Alta");
    registroPersona.registrar(52236487, "Jean Carlo Rado", 998426632, "jeancarlo@ulima.edu.pe", "Cambio de carrera", "doc4.pdf", "Ulima", "Baja");

    JOptionPane.showMessageDialog(this, "Expedientes de prueba registrados correctamente.");
    }//GEN-LAST:event_btnLlenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroIU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Prioridad;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel asunto;
    private javax.swing.JTextField asuntoTxt;
    private javax.swing.JRadioButton bAlta;
    private javax.swing.JRadioButton bBaja;
    private javax.swing.JRadioButton bExterno;
    private javax.swing.JRadioButton bUlima;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLlenar;
    private javax.swing.JButton btnVerLista;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dni;
    private javax.swing.JTextField dniTxt;
    private javax.swing.JLabel documento;
    private javax.swing.JTextField documentoTxt;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JLabel telefono;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JButton terminadoButton;
    // End of variables declaration//GEN-END:variables
}
